spring:
  application:
    name: MiddleService

application:
  registrationService:
    type: inMemory
  accountService:
    type: inMemory
  backendService:
    url: ${BACKEND_SERVICE_URL:http://localhost:8081}